CREATE TABLE GAB_3865_CRM_USR_DEF(
ID IDENTITY,
MODULEID INTEGER,
USER_ID CHAR(8),
DEFAULT_CHK BIT NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE GAB_3865_CRM_USR_DEF(ID IDENTITY,MODULEID INTEGER,USER_ID CHAR(8),DEFAULT_CHK BIT NOT NULL,PRIMARY KEY (ID));